### ISSUE TITLE
add a rev staked token

### ISSUE THREAD

**Issue by jimscarver** [rchain-community/rstake#9]
Issuing a rev-staked token for each rev deposited would:

prove ownership of staked rev
facilitate distribution of staking rewards
enable trading of staked rev

dckc commented 17 minutes ago
also: staked rev could use normal Mints and purses and skip the vault tedium.

We need a locker thingy to go with it so we can get on/off chain via the registry.

**Comment by jimscarver** [comment]
We could consider employing mailboxes for capability sharing. The model of  mailboxes and ballots could be used with tickets / unforgeable names https://github.com/rchain-community/rv2020/issues/12

**Comment by dckc** [comment]
closed? oh... https://github.com/rchain-community/rstake/issues/10
